### ISSUE TITLE
Continuation of this repository

### ISSUE THREAD

**Issue by Worstjibs** [Assasindie/DotnetOsrsApiWrapper#1]
Hi Assasindie, I've recently been working on a fork of this repo, and making improvements such as
- Use of HttpClient and Async calls
- New PlayerInfoService and interface, for improved testability
- New method to return list of PlayerInfo for mutliple Usernames

If you are interested, I would like to continue maintaining this repo and publish my changes to Nuget, as I have another project I have been working on which would benefit from this. If you are keen, I can open a PR for you to review? I'm new to Open Source; this would be my first collaboration.

**Comment by AlexB6773** [comment]
Yea mate go for it, good luck. If you want you can just completely take over and publish it under your own nuget package as I never bothered to setup automated updates from this repo to nuget and as you can probably tell havent really maintained the package either since first making it.

If you make under your own package I can link add link to it from the existing one as that is already marked as legacy.

**Comment by Worstjibs** [comment]
How about this, I can open a PR for you to review what I've done and merge in my changes, and then you can make me a Collaborator on the repo and publisher for the Nuget package, that way we don't end up with multiple packages?

**Comment by Worstjibs** [comment]
Hey just checking if you had a chance to look at my PR?
